server:
  port: 8081
 
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
 
sharding:
  jdbc:
    datasource:
      # 定义数据源ds0
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/user0?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
    config:
      sharding:
        props:
          sql.show: true
        tables:
          t_user:  #t_user表
            key-generator-column-name: id  #主键
            actual-data-nodes: ds0.t_user${0..2}    #数据节点,均匀分布
            table-strategy:  #分表策略
              inline: #行表达式
                sharding-column: id
                algorithm-expression: t_user${id % 3}  #按模运算分配
          #t_order: #t_order
          #  key-generator-column-name: id  #主键
          #  actual-data-nodes: ds0.t_order${0..2}    #数据节点,均匀分布
            
            
            
            
