server:
  port: 8081
 
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
 
sharding:
  jdbc:
    datasource:
      names: ds0,ds1
      # 数据源ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/user0?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/user1?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
    config:
      sharding:
        props:
          sql.show: true
        tables:
          t_user:  #t_user表
            key-generator-column-name: id  #主键
            actual-data-nodes: ds${0..1}.t_user${0..1}    #数据节点,均匀分布
            database-strategy:  #分库策略
                inline: #行表达式
                    sharding-column: id        #列名称，多个列以逗号分隔
                    algorithm-expression: ds${id % 2}    #按模运算分配
            table-strategy:  #分表策略
                standard:
                    sharding-column: id
                    precise-algorithm-class-name: org.springboot.sharding.jdbc3.apache.sharingalgorithm.IdSharingAlgorithm
                    range-algorithm-class-name: org.springboot.sharding.jdbc3.apache.sharingalgorithm.IdRangeSharingAlgorithm
            
